path:
    src:
        train: "parallel_corpora/train.en"
        valid: "parallel_corpora/valid.en"
        test: "parallel_corpora/test.en"
    tgt:
        train: "parallel_corpora/train.vi"
        valid: "parallel_corpora/valid.vi"
        test: "parallel_corpora/test.vi"

checkpoint:
    dir: "checkpoint"
    name: "checkpoint_best.pt"
    results: "results.csv"
    parallel_vocab: "parallel_vocab.pt" 
    dataloaders: "dataloaders.pt"

batch_size: 32
total_epoch: 3

clip: 1.0
warmup: 100

init_lr: !!float 1e-5
weight_decay: !!float 5e-4
adam_eps: !!float 5e-9
factor: 0.9
patience: 10

d_model: 512
max_len: 256
ffn_hidden: 2048
n_heads: 8
n_layers: 6
drop_prob: 0.1