path:
    src:
        train: "/content/EnVi_NMT/en-vi/train.tags.en-vi.clean.en"
        valid: "/content/EnVi_NMT/en-vi/valid.en"
        test: "/content/EnVi_NMT/en-vi/test.en"
    tgt:
        train: "/content/EnVi_NMT/en-vi/train.tags.en-vi.clean.vi"
        valid: "/content/EnVi_NMT/en-vi/valid.vi"
        test: "/content/EnVi_NMT/en-vi/test.vi"


batch_size: 32
epoch: 1
clip: 1.0
warmup: 100

init_lr: !!float 1e-5
weight_decay: !!float 5e-4
adam_eps: !!float 5e-9

factor: 0.9
patience: 10

d_model: 512
max_len: 256
ffn_hidden: 2048
n_heads: 8
n_layers: 6
drop_prob: 0.1